#ifndef __XML_GENERATED_DEPLOYMENT_H_
#define __XML_GENERATED_DEPLOYMENT_H_

#define POK_GENERATED_CODE	1

#define POK_NEEDS_LIBC_STDIO	1

#define POK_CONFIG_NB_THREADS	3

#define POK_NEEDS_ARINC653_PROCESS	1

#define POK_NEEDS_ARINC653_PARTITION	1

#define POK_NEEDS_ARINC653_TIME	1

#define POK_NEEDS_ARINC653	1

#endif